services:
  version: '3.8'

  services:
    postgres:
      image: postgres:13
      container_name: postgres-db
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: mydb
      ports:
        - "8001:80001"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - mynetwork

  volumes:
    postgres-data:

  networks:
    mynetwork:
      driver: bridge

